FROM node:20

WORKDIR /user/src/app

COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

# Expose the port the app runs in
EXPOSE 3001

# npm run start:prod
CMD ["npm", "run", "start:prod"]
